version: 2
jobs:
  test:
    docker: 
      - image: circleci/python:3.6.5
    steps:
      - checkout # check out the code in the project directory
      - run: 
          name: basic setup
          command: |
            ls
            pip install pipenv
            pipenv install --dev
            pipenv run pip freeze
      - run: 
          name: run pytest
          command: |
            pipenv run pytest
  build:
    docker: 
      - image: circleci/python:3.6.5
    steps:
      - checkout # check out the code in the project directory
      - run: 
          name: basic setup
          command: |
            ls
            pip install pipenv
            pipenv install --dev
            pipenv run pip freeze
      - run:
          name: verify git tag vs. version
          command: |
            echo $CIRCLE_TAG
            echo $CIRCLE_BRANCH
            pipenv run python setup.py verify
      - run:
          name: create package
          command: |
            pipenv run python setup.py sdist bdist_wheel
workflows:
  version: 2
  test_and_build:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - build:
          requires:
            - test
          filters:
            tags:
              only: /^(0|[1-9]\d*)(\.(0|[1-9]\d*)){2}$/ 
