version: 2
jobs:
  test:
    docker: 
      - image: circleci/python:3.6.5
    steps:
      - checkout # check out the code in the project directory
      - run: 
          name: Basic setup
          command: |
            ls
            pip install pipenv
            pipenv install --dev
            pipenv run pip freeze
      - run: 
          name: Run pytest
          command: |
            pipenv run pytest
  deploy:
    docker: 
      - image: circleci/python:3.6.5
    steps:
      - checkout # check out the code in the project directory
      - run: 
          name: Basic setup
          command: |
            ls
            pip install pipenv
            pipenv install --dev
            pipenv run pip freeze
      - run:
          name: Verify version and tag
          command: |
            pipenv run python setup.py verify
      - run:
          name: Create package
          command: |
            pipenv run python setup.py sdist bdist_wheel
      - run:
          name: Upload to PyPI
          command: |
            export TWINE_USERNAME=$PYPI_USERNAME_PRD
            export TWINE_PASSWORD=$PYPI_PASSWORD_PRD
            echo $TWINE_USERNAME
            pipenv run twine upload dist/*
workflows:
  version: 2
  test_and_build:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^(0|[1-9]\d*)(\.(0|[1-9]\d*)){2}$/ 
