version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
  test:
    docker: 
      - image: circleci/python:3.6.5
    steps:
      - checkout # check out the code in the project directory
      - run: ls
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
